name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest  # or windows-latest depending on your environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # specify the Python version used in your project

      - name: Install dependencies
        run: |
          # Skip installing pywin32 if not on Windows
          if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "Linux" ]; then
            pip install -r requirements.txt --no-deps
          elif [ "$(uname)" == "MINGW32_NT" ] || [ "$(uname)" == "MINGW64_NT" ]; then
            pip install -r requirements.txt
          fi

      # Optionally you can include additional steps like deployment, if required
